site_name: NWSL Advanced Analytics Documentation
site_description: Comprehensive documentation for the NWSL Advanced Analytics Intelligence platform
site_author: NWSL Analytics Team
site_url: https://platform.nwsldata.com/docs/

# Build configuration
site_dir: '../nwsl_data_platform/public/docs'
docs_dir: 'docs'

# Repository
repo_name: 'nwsl_data'
repo_url: 'https://github.com/tom-mcmillan/nwsl_data'
edit_uri: 'edit/main/docs/'

# Theme configuration - Clean minimal style like OpenAI
theme:
  name: material
  palette:
    scheme: default
    primary: black
    accent: black
  font:
    text: Inter
    code: 'Roboto Mono'
  features:
    - navigation.sections
    - navigation.top
    - search.highlight
    - content.code.copy
  custom_dir: overrides

# Extensions - Full Material support
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true

# Navigation
nav:
  - Home: index.md
  - About:
    - Mission & Vision: about/mission.md
    - Methodology: about/methodology.md
    - Why Advanced Analytics: about/why-advanced-analytics.md
  - Data Foundation:
    - Coverage & Quality: data/coverage.md
    - Data Sources: data/sources.md
    - Database Overview: data/database-overview.md

# Extra configuration
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tom-mcmillan/nwsl_data
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY

# Plugins
plugins:
  - search