# NWSL Advanced Analytics Intelligence Documentation
# Professional MkDocs Material Configuration

# Project Information  
site_name: NWSL Advanced Analytics Intelligence
site_url: https://tom-mcmillan.github.io/nwsl_data/
site_author: NWSL Analytics Team
site_description: >
  Comprehensive documentation for the NWSL Advanced Analytics Intelligence 
  platform - sophisticated sabermetrics-inspired analysis for women's professional soccer.

# Repository
repo_name: tom-mcmillan/nwsl_data
repo_url: https://github.com/tom-mcmillan/nwsl_data
edit_uri: edit/main/docs/

# Build Directory Configuration - GitHub Pages
site_dir: site  
docs_dir: docs

# Theme Configuration - Minimal Material Theme
theme:
  name: material
  language: en
  
  # Simple color palette
  palette:
    - scheme: default
      primary: indigo
      accent: indigo

# Advanced Markdown Extensions
markdown_extensions:
  # Standard Extensions
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      permalink_title: Permanent link
      
  # PyMdown Extensions for Advanced Formatting
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Professional Plugin Configuration
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
      lang: en
      min_search_length: 2

# Custom CSS disabled for baseline testing
# extra_css:
#   - stylesheets/nwsl-analytics-theme.css

# Minimal configuration
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tom-mcmillan/nwsl_data

# Navigation Structure - Available Documentation
nav:
  - Home: index.md
  
  - About:
    - about/index.md
    - Mission & Vision: about/mission.md
    - Methodology: about/methodology.md
    - Why Advanced Analytics: about/why-advanced-analytics.md
  
  - Data Foundation:
    - data/index.md
    - Coverage & Quality: data/coverage.md
    - Data Sources: data/sources.md
    - Database Overview: data/database-overview.md
  
  - Analytics Platform:
    - platform/index.md
    - NIR Composite Metrics: platform/nir-metrics.md
  
  - MCP Server:
    - mcp/index.md
    - Architecture: mcp/architecture.md
    - Tools & Capabilities: mcp/tools.md

# Copyright
copyright: >
  Copyright &copy; 2024 NWSL Advanced Analytics Intelligence - 
  <a href="#__consent">Change cookie settings</a>