[tool.ruff]
exclude = [
  "dev-notes/**",
  "scripts/data-extraction/**",
  "scripts/analysis/**",
  "scripts/data-processing/**",
  "scripts/database-management/**",
]

line-length = 120
target-version = "py310"

[[tool.mypy.overrides]]
module = ["pandas", "plotly", "plotly.*", "openai_agents"]
ignore_missing_imports = true

[tool.ruff.lint.per-file-ignores]
"tests/**" = ["B904"]
[tool.mypy]
files = ["src"]
ignore_missing_imports = true
explicit_package_bases = true
namespace_packages = true
