# Testing environment configuration
server:
  name: "NWSL Analytics - Testing"
  version: "1.0.0-test"
  debug: true
  port: 8001
  host: "localhost"
  reload: false

database:
  path: "../data/processed/nwsldata.db"
  timeout: 10
  pool_size: 2
  echo_sql: false

analytics:
  nir_calculation:
    enable_caching: false
    cache_ttl: 60
    debug_mode: true
  
  visualization:
    default_chart_size: [400, 300]
    enable_agent_fallback: true
    cache_charts: false

logging:
  level: "WARNING"
  format: "%(name)s - %(levelname)s - %(message)s"
  file: "dev-notes/logs/testing.log"

tools:
  player_search_limit: 5
  match_results_limit: 10
  team_history_seasons: 2
  enable_experimental_features: true

testing:
  mock_external_apis: true
  fast_mode: true
  skip_slow_tests: false